"""empty message

Revision ID: 333eddef8cb1
Revises: b8c9ed631c81
Create Date: 2025-06-16 15:58:03.049956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '333eddef8cb1'
down_revision: Union[str, None] = 'b8c9ed631c81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulationresult', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.Integer(), nullable=True))
        batch_op.drop_column('number')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulationresult', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('order')

    # ### end Alembic commands ###
