"""empty message

Revision ID: 6c1ca68459c1
Revises: 333eddef8cb1
Create Date: 2025-06-17 15:12:45.897107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '6c1ca68459c1'
down_revision: Union[str, None] = '333eddef8cb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulationresult', schema=None) as batch_op:
        batch_op.add_column(sa.Column('result_cumacs', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulationresult', schema=None) as batch_op:
        batch_op.drop_column('result_cumacs')

    # ### end Alembic commands ###
