"""empty message

Revision ID: b09f402cab79
Revises: 535c8f48210b
Create Date: 2025-06-11 15:04:33.553257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'b09f402cab79'
down_revision: Union[str, None] = '535c8f48210b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulationresult',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chosen_date', sa.Date(), nullable=False),
    sa.Column('departement', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('secteur', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('typologie', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fiche', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parameters', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('result_eur', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('simulationresult')
    # ### end Alembic commands ###
