"""empty message

Revision ID: b1247b972821
Revises: d9b508ddf956
Create Date: 2025-07-01 17:10:44.418070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'b1247b972821'
down_revision: Union[str, None] = 'd9b508ddf956'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mprarticles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pdf_file', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('link_article', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mprarticles')
    # ### end Alembic commands ###
