"""empty message

Revision ID: d9b508ddf956
Revises: 9fec882db469
Create Date: 2025-07-01 09:19:34.581237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'd9b508ddf956'
down_revision: Union[str, None] = '9fec882db469'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulationresult', schema=None) as batch_op:
        batch_op.add_column(sa.Column('beneficiary', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.drop_column('order')
    op.execute("UPDATE simulationresult SET beneficiary = 'Particulier'")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulationresult', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('beneficiary')
    op.execute("UPDATE simulationresult SET beneficiary = 'Particulier'")

    # ### end Alembic commands ###
